backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title Pl", name: "title", widget: "string" }
      - { label: "Title Eng", name: "titleEng", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description Pl", name: "description", widget: "string" }
      - { label: "Description Emg", name: "descriptionEng", widget: "string" }
      - { label: "Tags", name: "tags", widget: "string" }
      - {
          label: "Show more?",
          name: "showMore",
          widget: "boolean",
          default: false,
        }
      - {
          label: "GithubRepo",
          name: "githubRepo",
          widget: "string",
          required: false,
        }
      - { label: "Live", name: "live", widget: "string", required: false }
      - { label: "Body Pl", name: "body", widget: "markdown", required: false }
      - {
          label: "Body Eng",
          name: "bodyEng",
          widget: "markdown",
          required: false,
        }
  - name: "exercises"
    label: "Exercises"
    folder: "content/exercises"
    create: true
    # slug: "index"
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Title Pl", name: "title", widget: "string" }
      - { label: "Title Eng", name: "titleEng", widget: "string" }
      - {
          widget: relation,
          name: category,
          label: "Category",
          required: true,
          collection: categories,
          valueField: slug,
          searchFields: ["name"],
          displayFields: ["name"],
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description Pl", name: "description", widget: "string" }
      - { label: "Description Emg", name: "descriptionEng", widget: "string" }
      - { label: "Tags", name: "tags", widget: "string" }
      - {
          label: "GithubRepo",
          name: "githubRepo",
          widget: "string",
          required: false,
        }
      - { label: "Live", name: "live", widget: "string", required: false }
  - name: categories
    label: Excercise category
    folder: content/categories
    create: true
    slug: "{{slug}}"
    fields:
      - widget: string
        name: name
        label: Name
        required: true
      - widget: string
        name: slug
        label: Slug
        required: true
