backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title Pl", name: "title", widget: "string" }
      - { label: "Title Eng", name: "titleEng", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description Pl", name: "description", widget: "string" }
      - { label: "Description Emg", name: "descriptionEng", widget: "string" }
      - { label: "GithubRepo", name: "githubRepo", widget: "string" }
      - { label: "Live", name: "live", widget: "string" }
      - { label: "Is react?", name: "react", widget: "boolean", default: false }
      - {
          label: "Is gatsby?",
          name: "gatsby",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Is bootstrap?",
          name: "bootstrap",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Is mdbootstrap?",
          name: "mdbootstrap",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Is netlify?",
          name: "netlify",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Is netlifyCMS?",
          name: "netlifyCms",
          widget: "boolean",
          default: false,
        }
      - { label: "Body Pl", name: "body", widget: "markdown" }
      - { label: "Body Eng", name: "bodyEng", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title Pl, name: title, widget: string }
          - { label: Title Eng, name: titleEng, widget: string }
          - { label: Heading description PL, name: heading, widget: string }
          - { label: Heading description Eng, name: headingEng, widget: string }
          - {
              label: = Prof exp,
              name: professionalExp,
              widget: object,
              fields:
                [
                  { label: Title Pl, name: title, widget: string },
                  { label: Title Eng, name: titleEng, widget: string },
                  {
                    label: Subtitle line 1 Pl,
                    name: subtitleLine1,
                    widget: string,
                  },
                  {
                    label: Subtitle line 1 Eng,
                    name: subtitleLine1Eng,
                    widget: string,
                  },
                  {
                    label: Subtitle line 2 Pl,
                    name: subtitleLine2,
                    widget: string,
                  },
                  {
                    label: Subtitle line 2 Eng,
                    name: subtitleLine2Eng,
                    widget: string,
                  },
                  {
                    label: Subtitle line 3 Pl,
                    name: subtitleLine3,
                    widget: string,
                  },
                  {
                    label: Subtitle line 3 Eng,
                    name: subtitleLine3Eng,
                    widget: string,
                  },
                  { label: Description Pl, name: description, widget: text },
                  {
                    label: Description Eng,
                    name: descriptionEng,
                    widget: text,
                  },
                  {
                    label: Advertisement Pl,
                    name: advertisement,
                    widget: text,
                  },
                  {
                    label: Advertisement Eng,
                    name: advertisementEng,
                    widget: text,
                  },
                ],
            }
          - {
              label: = Prof exp first block,
              name: professionalExpFirstBlock,
              widget: object,
              fields:
                [
                  { label: Title 1 Pl, name: title1, widget: string },
                  { label: Title 1 Eng, name: title1Eng, widget: string },
                  {
                    label: Description 1 Pl,
                    name: description1,
                    widget: string,
                  },
                  {
                    label: Description 1 Eng,
                    name: description1Eng,
                    widget: string,
                  },
                  {
                    label: Description 2 Pl,
                    name: description2,
                    widget: string,
                  },
                  {
                    label: Description 2 Eng,
                    name: description2Eng,
                    widget: string,
                  },
                  {
                    label: Description 3 Pl,
                    name: description3,
                    widget: string,
                  },
                  {
                    label: Description 3 Eng,
                    name: description3Eng,
                    widget: string,
                  },
                  {
                    label: Advertisement Pl,
                    name: advertisement,
                    widget: text,
                  },
                  {
                    label: Advertisement Eng,
                    name: advertisementEng,
                    widget: text,
                  },
                ],
            }
          - {
              label: = Prof exp second block,
              name: professionalExpSecondBlock,
              widget: object,
              fields:
                [
                  { label: Title 1 Pl, name: title1, widget: string },
                  { label: Title 1 Eng, name: title1Eng, widget: string },
                  {
                    label: Description 1 Pl,
                    name: description1,
                    widget: string,
                  },
                  {
                    label: Description 1 Eng,
                    name: description1Eng,
                    widget: string,
                  },
                  {
                    label: Description 2 Pl,
                    name: description2,
                    widget: string,
                  },
                  {
                    label: Description 2 Eng,
                    name: description2Eng,
                    widget: string,
                  },
                  {
                    label: Description 3 Pl,
                    name: description3,
                    widget: string,
                  },
                  {
                    label: Description 3 Eng,
                    name: description3Eng,
                    widget: string,
                  },
                  {
                    label: Advertisement Pl,
                    name: advertisement,
                    widget: text,
                  },
                  {
                    label: Advertisement Eng,
                    name: advertisementEng,
                    widget: text,
                  },
                ],
            }
          - {
              label: = Education,
              name: education,
              widget: object,
              fields:
                [
                  { label: Title PL, name: title, widget: string },
                  { label: Title Eng, name: titleEng, widget: string },
                  { label: Time 1, name: time1, widget: string },

                  {
                    label: Description 1 Pl,
                    name: description1,
                    widget: string,
                  },
                  {
                    label: Description 1 Eng,
                    name: description1Eng,
                    widget: string,
                  },
                  { label: Time 2, name: time2, widget: string },
                  {
                    label: Description 2 Pl,
                    name: description2,
                    widget: string,
                  },
                  {
                    label: Description 2 Eng,
                    name: description2Eng,
                    widget: string,
                  },
                  { label: Time 3, name: time3, widget: string },
                  {
                    label: Description 3 Pl,
                    name: description3,
                    widget: string,
                  },
                  {
                    label: Description 3 Eng,
                    name: description3Eng,
                    widget: string,
                  },
                ],
            }
          - { label: Rodo PL, name: rodo, widget: text }
          - { label: Rodo Eng, name: rodoEng, widget: text }
