backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "GithubRepo", name: "githubRepo", widget: "string" }
      - { label: "Live", name: "live", widget: "string" }
      - { label: "Is react?", name: "react", widget: "bolean", default: true}}
      - { label: "Is gatsby?", name: "gatsby", widget: "bolean", default: true}}
      - { label: "Is bootstrap?", name: "bootstrap", widget: "bolean", default: true}}
      - { label: "Is mdbootstrap?", name: "mdbootstrap", widget: "bolean", default: true}}
      - { label: "Is netlify?", name: "netlify", widget: "bolean", default: true}}
      - { label: "Is netlifyCMS?", name: "netlifyCms", widget: "bolean", default: true}}
      - { label: "Body", name: "body", widget: "markdown" }
